### ISSUE TITLE
Update chart to use Confluent Kafka version 7

### ISSUE THREAD

**Issue by survivant** [confluent-helm-charts/cp-helm-charts#2]
Now that version 7.x is release, it could be useful to have the chart updated to the latest version

I created a umbrella chart to install the version 6.2 with 1 replica and with persistance.

````
apiVersion: v2
name: kafka
description: Chart for CICD
type: application
version: 0.1.20-dev
appVersion: 1.0.0
dependencies:
  - name: cp-helm-charts
    version: 0.6.1
    repository: "@confluentinc"
    condition: kafka.enabled
    alias: kafka
````

````
kafka:
  enabled: true

  cp-zookeeper:
    servers: 1
    imageTag: 6.2.0
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    persistence:
      enabled: false
      dataDirStorageClass: sc-localpv
      dataLogDirStorageClass: sc-localpv
      storageClass: sc-localpv

  cp-kafka:
    brokers: 1
    imageTag: 6.2.0
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 4000m
        memory: 4Gi
      requests:
        cpu: 2000m
        memory: 2Gi
    configurationOverrides:
      "offsets.topic.replication.factor": "1"
      "metrics.topic.replication.factor": "1"
      "default.replication.factor": 1
      "confluent.metrics.reporter.topic.replicas": "1"
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_LOG_CLEANUP_POLICY: "compact,delete"
      KAFKA_LOG_CLEANER_ENABLE: "true"
      "listener.security.protocol.map": "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_2:PLAINTEXT,EXTERNAL_3:PLAINTEXT"
      #"advertised.listeners": "EXTERNAL://192.168.50.30:31090,EXTERNAL_2://${HOST_IP}:19092,EXTERNAL_3://localhost:29092"
      "advertised.listeners": "EXTERNAL://192.168.50.30:31090,EXTERNAL_3://localhost:29092"
      #"listeners": "PLAINTEXT://0.0.0.0:9202,EXTERNAL://localhost:31090,EXTERNAL_3://localhost:29092"

  cp-kafka-connect:
    imageTag: 6.2.0
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
    configurationOverrides:
      "config.storage.replication.factor": "1"
      "offset.storage.replication.factor": "1"
      "status.storage.replication.factor": "1"
      "confluent.metrics.reporter.topic.replicas": "1"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1

  cp-schema-registry:
    imageTag: 6.2.0
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
    enabled: true
    configurationOverrides:
      "kafkastore.timeout.ms": 3000
      "kafkastore.init.timeout.ms": 180000
      "kafkastore.topic.replication.factor": 1
      "confluent.metrics.reporter.topic.replicas": "1"
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1

  cp-kafka-rest:
    imageTag: 6.2.0
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi

  cp-ksql-server:
    imageTag: 6.2.0
    resources:
      limits:
        cpu: 4000m
        memory: 3Gi
      requests:
        cpu: 3000m
        memory: 2Gi

  cp-control-center:
    imageTag: 6.2.0
    resources:
      limits:
        cpu: 4000m
        memory: 4Gi
      requests:
        cpu: 3000m
        memory: 2Gi
    configurationOverrides:
      "replication.factor": "1"
      "internal.topics.replication": "1"
      "monitoring.interceptor.topic.replication": "1"
      "metrics.topic.replication": "1"
      "command.topic.replication": "1"
      "confluent.metrics.reporter.topic.replicas": "1"
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1

````
